phase: training
# testing
# training
# validation
phases:
  - training
  - validation
  - testing
data_path: /home/marcel/workspace/datasets/waymo-od
raw_data_path: /media/marcel/Data1/Raw
exploring:
  idx: null
  frame_num: -1
  col: 21
explore_data_deep: False
grid_step: 8
dataset: waymo    # waymo, kitti, kitti-360
