phase: testing
# testing
# validation
data_path: data/
targets: targets
raw_data_path: /media/marcel/Data1/
# /media/marcel/Data1/
# raw/
explore_data: True
exploring:
  view: 0
  idx: 0
  frame_num: -1
  col: 180
explore_data_deep: False
num_views: 3
num_threads: 1
dataset_name: waymo-od-lidar
num_zips_training: 16
num_zips_validation: 4
num_zips_testing: 3
