phase: training
# testing
# training
# validation
phases:
  - training
  - validation
  - testing
data_path: /home/marcel/workspace/datasets/waymo-od
raw_data_path: /media/marcel/Data1/Raw
exploring:
  idx: 111
  frame_num: 12
  col: 180
explore_data_deep: False
grid_step: 8
SemSeg:
  for_dataset: kitti
