phase: validation
# testing
# training
# validation
phases:
  - training
  - validation
  - testing
data_path: /home/marcel/datasets/
raw_data_path: /media/marcel/Data1/Raw/
# /media/marcel/Data1/Raw/
# raw/
explore_data: True
exploring:
  view: 1
  random_idx: False
  idx: 13
  frame_num: -1
  col: 180
explore_data_deep: False
num_views: 3
num_threads: 1
num_zips_training: 15
num_zips_validation: 3
num_zips_testing: 3
