phase: training
# testing
# training
# validation
phases:
  - training
  - validation
  - testing
data_path: C:\Users\marce\Documents\datasets
# /home/marcel/datasets/
# data/
raw_data_path: C:\Users\marce\Documents\raw
# /media/marcel/Data1/Raw/
# /media/marcel/external_ssd/datasets/
# raw/
explore_data: True
exploring:
  view: 1
  random_idx: False
  idx: 13
  frame_num: -1
  col: 180
explore_data_deep: False
num_views: 3
num_threads: 1
num_zips_training: 15
num_zips_validation: 3
num_zips_testing: 3
grid_step: 8
SemSeg:
  for_dataset: ameise
