phase: training
# testing
# training
# validation
phases:
  - training
  - validation
  - testing
data_path: /home/marcel/workspace/datasets
raw_data_path: /home/marcel/workspace/datasets/raw/
exploring:
  idx: 377 #165, 377
  frame_num: 1  #0, 1
  col: 234
explore_data_deep: True
grid_step: 8
dataset: waymo    # waymo, kitti, kitti-360
generator: bbox   # bbox, semantic, default
