phase: testing
# testing
# training
# validation
phases:
  - training
  - validation
  - testing
data_path: data
raw_data_path: raw
exploring:
  view: 1
  random_idx: False
  idx: 0
  frame_num: -1
  col: 180
explore_data_deep: False
grid_step: 4
SemSeg:
  for_dataset: kitti
