phase: training
# testing
# training
# validation
phases:
  - training
  - validation
  - testing
data_path: /mnt/workspace/datasets
raw_data_path: /mnt/workspace/Raw
exploring:
  idx: null #165, 377 42, 29
  frame_num: 0  #0, 1
  col: 234
explore_data_deep: True
grid_step: 8
dataset: kitti    # waymo, kitti, kitti-360
generator: default   # bbox, semantic, default
