phase: validation
# testing
# training
# validation
data_path: /home/marcel/datasets/ameise_okt23/
targets: targets_from_lidar
raw_data_path: /media/marcel/Data1/ameise/
# /media/marcel/Data1/
# raw/
explore_data: False
exploring:
  view: 1
  random_idx: False
  idx: 56
  frame_num: -1
  col: 180
explore_data_deep: False
num_views: 3
num_threads: 1
dataset_name: ameise-test
num_zips_training: 15
num_zips_validation: 3
num_zips_testing: 3
selected_dataset: ameise
cameras_to_use: [1]
