phase: training
# testing
# training
# validation
phases:
  - training
  - validation
  - testing
data_path: /media/marcel/Data1/datasets/train_on_kitti
raw_data_path: /media/marcel/Data1/Raw
exploring:
  enable: False
  view: 1
  random_idx: False
  idx: 13
  frame_num: -1
  col: 180
explore_data_deep: False
grid_step: 4
SemSeg:
  for_dataset: kitti
