phase: testing
# testing
# training
# validation
phases:
  - training
  - validation
  - testing
data_path: /media/marcel/Data1/Datasets
raw_data_path: /media/marcel/Data1/Raw
exploring:
  idx: null
  frame_num: 0
  col: 180
explore_data_deep: False
grid_step: 8
SemSeg:
  for_dataset: kitti
